#!/usr/bin/env python3
import sys
import argparse
import os
from PIL import ImageOps
from PIL import Image
import numpy as np


def convert_to_c_array(input_paths, output_path, orientation, dither, gamma):

    with open(output_path, 'w') as f:
        f.write('/* Auto-generated by convert_image.py */\n')
        f.write('#pragma once\n')
        f.write('#include <stdint.h>\n\n')
        
        array_names = []
        
        for input_path in input_paths:
            print(f"processing: {input_path}")
            img = Image.open(input_path)
            
            target_size = (480, 800) if orientation == 'portrait' else (800, 480)
            
            img = ImageOps.pad(img.convert('RGB'), target_size, color=(255, 255, 255))
            
            if orientation == 'portrait':
                img = img.rotate(90, expand=True) 
            
            # Apply gamma correction to lighten the image (gamma < 1.0)
            if gamma != 1.0:
                img = img.point(lambda p: 255 * (p / 255) ** gamma)
            
            if dither:
                # Create a 4-level grayscale palette matched to physical shades
                # Black=0, Dark Gray=85, Light Gray=128, White=255
                pal_img = Image.new("P", (1, 1))
                pal_img.putpalette([0, 0, 0, 85, 85, 85, 128, 128, 128, 255, 255, 255] + [0]*756)
                # Quantize with Floyd-Steinberg dithering (dither=1)
                img = img.quantize(palette=pal_img, dither=1)
                data_2bit = np.array(img).astype(np.uint8)
            else:
                img = img.convert('L')
                data = np.array(img)
                # Map based on midpoints between 0, 85, 128, 255
                data_2bit = np.zeros_like(data, dtype=np.uint8)
                data_2bit[data >= 42] = 1
                data_2bit[data >= 106] = 2
                data_2bit[data >= 192] = 3
            
            # Pack 4 pixels into 1 byte
            packed = np.zeros((data_2bit.shape[0], data_2bit.shape[1] // 4), dtype=np.uint8)
            for i in range(4):
                packed |= (data_2bit[:, i::4] << (6 - 2*i))
                
            base_name = os.path.basename(input_path).replace('.png', '').replace('.jpg', '').replace('-', '_').replace(' ', '_')
            array_name = f"img_data_{base_name}"
            array_names.append(array_name)
            
            f.write(f'const uint8_t {array_name}[96000] = {{\n')
            for row in packed:
                line = ', '.join([f'0x{b:02x}' for b in row])
                f.write(f'    {line},\n')
            f.write('};\n\n')
        
        f.write(f'const uint8_t* const image_array[{len(array_names)}] = {{\n')
        for name in array_names:
            f.write(f'    {name},\n')
        f.write('};\n')
        
        f.write(f'const int image_count = {len(array_names)};\n')
        
    print(f"Successfully converted {len(input_paths)} images to {output_path} ({orientation} mode, 2-bit grayscale, dither={dither})")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Convert images to 2-bit C arrays for the X4 E-Ink display.')
    parser.add_argument('inputs', nargs='+', help='Paths to the input image files (e.g., image1.png image2.png)')
    parser.add_argument('--output', required=True, help='Path to the output C header file (e.g., images.h)')
    parser.add_argument('--orientation', choices=['portrait', 'landscape'], default='portrait',
                        help='Orientation of the image (default: portrait)')
    parser.add_argument('--dither', action='store_true', help='Enable Floyd-Steinberg dithering')
    parser.add_argument('--gamma', type=float, default=0.8, help='Gamma correction factor (default 0.8, <1.0 lightens)')
    
    args = parser.parse_args()
    convert_to_c_array(args.inputs, args.output, args.orientation, args.dither, args.gamma)
